title: Définir les broches d'un potentiomètre
hero_image: images/banner.png
description: Comment définir les broches d'un potentiomètre sur le Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - 
    title: Définir les broches d'un potentiomètre
